name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - pip
  - matplotlib
  - ipywidgets
  - seaborn
  - IPython
  - statsmodels
  - patsy
  - opencv-python
