name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - pip
  - pip:
    - opencv-python
  - matplotlib
  - ipywidgets
  - seaborn
  - IPython
  - statsmodels
  - patsy
